### PR TITLE
chore: generate project using repo-config

### PR DESCRIPTION
**Pull request by sandovalrr**

### CODE REVIEW

**Comment by cwasicki** [comment]
@sandovalrr  All files are commited as generated or did you make any modifications?

**Comment by cwasicki** [comment]
>chore: chore: generate project using repo-config

One `chore` can be removed from commit title.

**Comment by sandovalrr** [comment]
> all files are commited as generated or did you make any modifications?

All files are committed as generated.

**Review by cwasicki — APPROVED** [review]
LGTM

**Pull request closed without merging**
