### PR TITLE
feat: Add secure connection using gRPC SSL credentials

### PR DESCRIPTION
**Pull request by sandovalrr**

### CODE REVIEW

**Comment by Marenz** [comment]
Short discussion summary with Richard:

* Possibly easier to pass in the channel from outside to init
* Alternatively a flag "ssl" or "tls" that can be given in init?

It's certainly desirable to be able to test insecure channels, but the tests/ module could also just mock those parts.

**Comment by llucax** [comment]
The new (unreleased) version of https://github.com/frequenz-floss/frequenz-client-base-python/ should help with this.

Maybe you can try out the branch and if it works well we can release it.

**Comment by flora-hofmann-frequenz** [comment]
> Maybe you can try out the branch and if it works well we can release it.

We will look into this, but currently blocked and thus updated this PR first.

**Comment by flora-hofmann-frequenz** [comment]
Closed as we continue working on #76

**Pull request closed without merging**
